[".zsh/zsh-autocomplete"]
exact = true
refreshPeriod = "168h"
stripComponents = 1
type = "archive"
url = "https://github.com/marlonrichert/zsh-autocomplete/archive/master.tar.gz"

[".zsh/zsh-syntax-highlighting"]
exact = true
refreshPeriod = "168h"
stripComponents = 1
type = "archive"
url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz"
